#!/usr/bin/env bash
#Install nginx on your web-01 server
#Nginx should be listening on port 80
#When querying Nginx at its root / with a GET request (requesting a page)
#using curl, it must return a page that contains the string Hello World!
#You can’t use systemctl for restarting nginx
#-y picks yes for every prompt during installation
#default html webpage of Nginx if found in /var/www/html/index.nginx-debian.html

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx start
