#!/usr/bin/env bash

#Install nginx on your web-01 server
#Nginx should be listening on port 80
#When querying Nginx at its root / with a GET request (requesting a page)
#using curl, it must return a page that contains the string Hello World!
#You can’t use systemctl for restarting nginx
#-y picks yes for every prompt during installation
#default html webpage of Nginx if found in /var/www/html/index.nginx-debian.html

MY_PATH="/etc/nginx/sites-available/default"
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP' #Allow incoming traffic from port 80(HTTP)
echo "Hello World!" > /var/www/html/index
sudo sed -i '/listen 80 default_server/a rewrite redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4/ permanent;' $MY_PATH 
sudo service nginx restart
