#!/usr/bin/env bash
#A new Nginx server configured so that /redirect_me is redirecting to another page

MY_PATH="/etc/nginx/sites-available/default"
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World" | sudo tee /var/www/html/index.html > /dev/null
sudo sed -i '46i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' $MY_PATH
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null
sed -i "46i error_page 404 /custom_404.html;" $MY_PATH
sudo service nginx restart
