#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script
# Make sure that your servers are configured with the right hostnames:

# update package repo
sudo apt-get -y update

# Install HAproxy
sudo apt-get -y install haproxy=2.0.\*

# Enable HAProxy service at startup i.e HAproxy can be managed via init script
sudo echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Backup original config file before modifying it
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

# Append the configuration in the config file
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 7670-web-01 54.237.54.19:80 check
   server 7670-web-02 54.146.64.168:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

# Restart HAproxy
sudo service haproxy start
