#!/usr/bin/env bash
# Installs and setup haproxy

sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.2
sudo apt-get install -y haproxy=2.2.\*

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Listen to web1 and web2 servers
echo "
   listen load_balancer
   bind *:80
   mode http
   option httpclose
   balance roundrobin
   option forwardfor
   server web-01 54.237.54.19:80 check
   server web-02 54.146.64.168:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

service haproxy start
