#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a compressed
# archive out of it.

day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")

file_name="$day-$month-$year.tar.gz"

# Perform database backup using mysqldump to a name file
mysqldump --all-databases -u root --password="$1" > backup.sql

# Compress the backup.sql file with compressed file name $file_name
tar -czvf "$file_name" backup.sql
