#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80 in shorter way.
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill -9 "$(cat /var/run/nginx.pid)"
