#!/usr/bin/env bash
# A bash (init) script that manages manage_my_process

FILE="/var/run/my_process.pid"

start_n_disp()
{
	./manage_my_process &
	echo "$!" > "$FILE"
}
stop_n_disp()
{
	sudo pkill -f  "./manage_my_process"
	rm "$FILE"
}

if [ "$1" == "start" ]; then
	echo "manage_my_process started";
	start_n_disp

	elif [ "$1" == "stop" ]; then
		echo "manage_my_process stopped";
		stop_n_disp

	elif [ "$1" == "restart" ]; then
		echo "manage_my_process restarted"
		stop_n_disp
		start_n_disp
	else
		echo "Usage: manage_my_process {start|stop|restart}"
fi
