#!/usr/bin/env bash
# This Bash script displays Best School 9 times and the
# 9th iteration displays Hi in place of Best School

i=1

while [ $i -le 10 ]; do
	
	echo "Best School"
	if [ "$i" -eq 9 ]; then
		echo "Hi"
	fi
	i=$((i+1))
done
