#!/usr/bin/env bash
# This Bash script loops from 1 - 10. On the 4th iteration, it
# displays `bad luck`, on 8th `good luck' and the rest `Best School

i=1

while [ $i -le 10 ]; do
	if [ $i -eq 4 ]; then
		echo "bad luck"
	elif [ $i -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
