#!/usr/bin/env bash
# Displays numbers from 1 - 20 and n 5th, 10th and 18th iteration,
#replace the number with `bad luck from china`, `bad luck from Japan`
#and `bad luck from italy`.

i=1

while [ $i -le 20 ]; do
	echo $i

	case $i in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;
	esac
	i=$((i+1))
done
