#!/usr/bin/env bash
# Displays numbers from 1 - 20 and n 5th, 10th and 18th iteration,
#replace the number with `bad luck from china`, `bad luck from Japan`
#and `bad luck from italy`.

i=1

while [ $i -le 20 ]; do
	echo $i
	if [ $i -eq 4 ]; then
		echo "bad luck from China"
	elif [ $i -eq 9 ]; then
		echo "bad luck from Japan"
	elif [ $i -eq 17 ]; then
		echo "bad luck from Italy"
	fi
	i=$((i+1))
done
