#!/usr/bin/env bash
# This Bash script displays the time for 12 hours and 59 minutes
# using while loop

hour=0

while [ $hour -lt 12 ]; do
	echo "Hour: $hour"
	
	hour=$((hour+1))

	minutes=1
	while [ $minutes -lt 60 ]; do
		echo $minutes
		minutes=$((minutes+1))
	done
done
