#!/usr/bin/bash
# Installs firewall and congigures it such that it blocks all incoming
# traffics except port 22, 443, 80

# install ufw that support both IPv4 and IPv6

sudo apt-get -y install ufw
sudo sed -i "s/IPV6=no/IPV6=yes/" /etc/default/ufw
sudo ufw default allow outgoing
sudo ufw default deny incoming

# set ports to accepts traffic from
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

# Enable firewall
sudo ufw enable
